# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    
    - name: Cache Swift Packages
      id: cache-swiftpm
      uses: actions/cache@v4
      with:
        path: |
          .build
          ~/Library/Developer/Xcode/DerivedData
          ~/Library/Caches/org.swift.swiftpm
        key: macos-swiftpm-${{ runner.os }}-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          macos-swiftpm-${{ runner.os }}-
        enableCrossOsArchive: false
        fail-on-cache-miss: false
        lookup-only: false
        save-always: true

    - name: Build HamsteriOS
      run: swift build -v
      working-directory: Packages/HamsteriOS

    - name: Run HamsteriOS tests
      run: swift test -v
      working-directory: Packages/HamsteriOS


